#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the `wizard` skill.
#
# Everything above the STAGES marker is the wizard library and is identical in
# every wizard: do not hand-edit it. Author the per-step stages below it.

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Wizard library
# ─────────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Set by the author at the top of the STAGES section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WROTE_ENV=()     # KEYs upserted into ENV_FILE this run
WROTE_SECRET=()  # CI secret names set this run
PENDING=()       # things the wizard could not do — surfaced by finish()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
bad()  { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"; }

# manual "description" — record something the human must do by hand. Always
# surfaces in the closing summary, so an un-automatable step is never silently
# dropped just because the wizard could not perform it.
manual() { PENDING+=("$1"); warn "by hand: $1"; }

# require CMD ["reason"] — assert a prerequisite tool exists. Missing tools are
# recorded rather than fatal: the human can still complete the browser work.
# Under `set -e` a bare `require foo` would exit on a miss, which defeats that —
# always call it as `if require foo; then …` or `require foo || true`.
require() {
  if command -v "$1" >/dev/null 2>&1; then
    return 0
  fi
  manual "install \`$1\`${2:+ — $2}"
  return 1
}

# banner "Title" — opening frame.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard says exactly what to do and captures\n' "$DIM"
  printf '  what you copy back. Ctrl-C any time and re-run later — values already\n'
  printf '  saved are offered back as defaults.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, announce the stage, show progress.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# open_url URL — open in the human's browser, cross-platform including WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "no browser opener found — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "could not open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; succeeds on yes. Gate irreversible actions.
confirm() {
  local reply=""
  printf '  %s? %s%s [y/N] ' "$YELLOW" "$1" "$RESET"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  [[ -n "$line" ]] || return 1
  printf '%s' "${line#*=}"
}

_prompt() {
  local prompt="$1" current="$2"
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
}

# ask KEY "Prompt" — read a visible value into $KEY, defaulting to what is
# already in ENV_FILE so re-runs are cheap.
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  _prompt "$prompt" "$current"
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — as ask, with hidden input.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  _prompt "$prompt" "$current"
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — idempotent upsert into ENV_FILE.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  # Re-writing a key on a later stage or a re-run must not double-count it in
  # the closing summary.
  case " ${WROTE_ENV[*]-} " in *" $key "*) ;; *) WROTE_ENV+=("$key") ;; esac
  ok "wrote $key → $ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret. Records a manual
# fallback rather than failing when gh is unavailable.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WROTE_SECRET+=("$name")
      ok "set CI secret $name"
      return 0
    fi
  fi
  manual "set CI secret $name (\`gh secret set $name\`)"
}

# set_var NAME VALUE — set a non-secret GitHub Actions repo variable.
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      ok "set CI variable $name"
      return 0
    fi
  fi
  manual "set CI variable $name (\`gh variable set $name\`)"
}

# check "description" <command...> — verify a manual step actually took effect.
# On failure the human may retry (they just changed something) or skip, in
# which case it lands in the closing summary. A step with an observable result
# is a step the human cannot silently get wrong.
check() {
  local description="$1"; shift
  while true; do
    printf '  %s⋯%s checking %s\n' "$DIM" "$RESET" "$description"
    if "$@" >/dev/null 2>&1; then
      ok "$description"
      return 0
    fi
    bad "$description — not yet"
    if confirm "Retry the check?"; then
      continue
    fi
    manual "verify: $description"
    return 1
  done
}

# await "description" <command...> — poll until a command succeeds, for changes
# that propagate (DNS, certificate issuance, deploys). Honours WAIT_TRIES and
# WAIT_SECONDS; falls through to check()'s retry/skip prompt when it gives up.
await() {
  local description="$1"; shift
  local tries="${WAIT_TRIES:-20}" gap="${WAIT_SECONDS:-15}" i=1
  printf '  %s⋯%s waiting for %s %s(up to %s min)%s\n' \
    "$DIM" "$RESET" "$description" "$DIM" "$(( tries * gap / 60 ))" "$RESET"
  while (( i <= tries )); do
    if "$@" >/dev/null 2>&1; then
      ok "$description"
      return 0
    fi
    printf '  %s  attempt %s/%s — retrying in %ss%s\r' "$DIM" "$i" "$tries" "$gap" "$RESET"
    sleep "$gap"
    (( i++ ))
  done
  printf '\n'
  bad "$description — still not visible after $(( tries * gap / 60 )) min"
  note "propagation can take longer; this is not necessarily an error"
  check "$description" "$@" || true
}

# finish — closing summary. Everything recorded by manual() surfaces here.
finish() {
  _clear
  printf '\n%s%s  ✓ Done%s\n\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WROTE_ENV[@]} ))    && note "wrote ${#WROTE_ENV[@]} value(s) to $ENV_FILE: ${WROTE_ENV[*]}"
  (( ${#WROTE_SECRET[@]} )) && note "set ${#WROTE_SECRET[@]} CI secret(s): ${WROTE_SECRET[*]}"
  if (( ${#PENDING[@]} )); then
    printf '\n'
    warn "still to do by hand:"
    local item
    for item in "${PENDING[@]}"; do note "  - $item"; done
  fi
  printf '\n'
}

# ─────────────────────────────────────────────────────────────────────────────
# STAGES — author below. One stage() per step the human takes.
# Replace the example. Set the totals to match the stages you write.
# ─────────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1
TOTAL_MINUTES=5

banner "Example setup"

stage "Stripe — API keys" 5
say "We'll grab your Stripe test keys and store them for local dev and CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "Copy the Publishable key (it starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"   # CI needs this one

finish
